{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-provider-ssh.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter-provider-ssh.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "karpenter-provider-ssh.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: {{ .Values.controller.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
{{- end }}
